version: "3.8"
services:
  redis:
    image: redis
    environment:
      REDIS_PASSWORD: redis
    ports:
      - "6379"
    networks:
      - backend

  server:
    image: stensh1/host-editor
    privileged: true
    ports:
      - "8080:8080"
      - "9000:9000"
    networks:
      - backend
    depends_on:
      - redis
    links:
      - redis

networks:
  backend: